### PR TITLE
Added support for video...

### PR DESCRIPTION
**Pull request by memst**
Added support for video, standardized media handling through mediaContainer.

### CODE REVIEW

**Comment by memst** [comment]
I could have also merged the commits myself  ¯\_(ツ)_/¯

**Comment by makuto** [comment]
I'm really excited for this one. Checking it out locally now :).

**Comment by makuto** [comment]
Works perfectly. Excellent work! I'll take a look at the SSL change next

**Comment by memst** [comment]
nice.

**Pull request merged**
