### PR TITLE
Refactor for nicer code organization

### PR DESCRIPTION
**Pull request by Amar1729**
Related - #32 , #52 , maybe #29 

1. Removed and organized unnecessary imports from code (now most imports are organized by whether they're built-in, third-party, or local)
2. Added a pyproject.toml (using `poetry`)
3. Added/removed a few things from the `.gitignore` (e.g. the sublime-workspace file is typically not versioned)
4. Moved around code a little bit to introduce better organization. I created a `downloaders` submodule where any files related to downloading content go, and a `utils` submodule where general utility code goes. Figured this could be a good initial hit at organizing the code into a more traditional structure.

Moved files and their diffs against current `master` shown below:
```
 imageSaver.py => downloaders/imageSaver.py                         | 28 ++++++++---------
 imgurDownloader.py => downloaders/imgurDownloader.py               | 18 ++++++-----
 pixivScraper.py => downloaders/pixivScraper.py                     |  5 ++-
 redditScraper.py => downloaders/redditScraper.py                   |  9 +++---
 redditUserImageScraper.py => downloaders/redditUserImageScraper.py | 28 +++++------------
 tumblrScraper.py => downloaders/tumblrScraper.py                   | 10 ++++--
 videoDownloader.py => downloaders/videoDownloader.py               |  8 +++--
 pyproject.toml                                                     | 29 +++++++++++++++++
 crcUtils.py => utils/crcUtils.py                                   |  0
 logger.py => utils/logger.py                                       |  0
 utilities.py => utils/utilities.py                                 |  2 ++

```

Mostly here to serve as a reference, it doesn't have to be merged into master. I know you're a bit wary of making large changes because of lack of regression testing - these changes seem to work on my end, but there could be a downloader I missed.

If you do want me to merge this, I can squash commits and add a note in the README about poetry usage.

### CODE REVIEW

**Comment by Amar1729** [comment]
I initially tried refactoring the python code and templates into an `app` directory, since that's common convention for webapp code ([example structure](https://gist.github.com/JeOam/ee5a7022dd5616fa6eaf)) but it turned out out to be a large refactor and changing imports in python as well as links in HTML/js, so I abandoned that for now.

**Comment by makuto** [comment]
Thanks for the good work! It looks like you're missing the latest changes to master, which include adding Pinterest support. It'll probably slot right in to the new organization. I'm going to clone your branch and try the new poetry workflow today :).

**Comment by makuto** [comment]
I was able to successfully build with Pyinstaller within the poetry-created virtual environment, so I will pull this change once the following things are done:
- Add Pinterest downloader and its necessary changes
- Downgrade required python version to 3.5, which is what Ubuntu 18.04 LTS supports, as well as whatever Debian I have installed on my Raspberry Pi

I don't think it'll be too hard to add the Pinterest stuff myself, so I might just do that

**Comment by makuto** [comment]
Merged! Thanks for the good work!

**Comment by Amar1729** [comment]
No problem, happy to help!
As a side-note, `poetry install -E security` is only necessary if the user wants to use authentication and SSL encryption. `poetry install` is sufficient otherwise.

**Pull request merged**
